---
- name: Script {{ sh | basename }} {{ sh_arg }}
  script: '"{{ sh_script_path }}{{ sh }}" {{ sh_arg }}'
  register: servermonkey_sh_shell
  changed_when: servermonkey_sh_shell.stdout != ""
  become: true

- name: Log script
  include_role: name=servermonkey.ww_logger
  vars:
    ww_log: '{{ servermonkey_sh_shell }}'
    ww_logfile: '{{ ansible_parent_role_names[1] }}_{{ sh | basename }}{{ sh_arg }}'
  when: servermonkey_sh_shell.changed